Repository falcosecurity/.github, pull requests merged in 2020-12, with the labels that each got.

#15 docs: update zoom link in CONTRIBUTING
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/XS

#17 docs(OWNERS): adding my self to the OWNERS file
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/XS

#14 docs: correct zoom room in SUPPORT
  SUPPORT.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#21 update: maintainers list
  maintainers.yaml
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/L

#22 update: maintainers list
  maintainers.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/XS
