Repository falcosecurity/.github, pull requests merged in 2021-01, with the labels that each got.

#23 update: maintainers list
  maintainers.yaml
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#24 update: maintainers list
  maintainers.yaml
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#25 docs: markdown governance
  GOVERNANCE.md
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/M

#26 docs(GOVERNANCE.md): correct typo
  GOVERNANCE.md
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/XS

#27 [update] CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#28 update: maintainers list
  maintainers.yaml
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS
