Repository falcosecurity/.github, pull requests merged in 2022-07, with the labels that each got.

#85 update: maintainers list
  maintainers.yaml
Labels: dco-signoff: yes, needs-kind, lgtm, approved, size/M

#84 update(OWNERS): move inactive maintainers to emeritus approvers
  OWNERS
Labels: dco-signoff: yes, lgtm, approved, size/XS, kind/documentation

#87 update: maintainers list
  maintainers.yaml
Labels: dco-signoff: yes, lgtm, approved, kind/documentation, size/L

#88 update: maintainers list
  maintainers.yaml
Labels: dco-signoff: yes, needs-kind, size/S, lgtm, approved
