Repository falcosecurity/.github, pull requests merged in 2022-08, with the labels that each got.

#90 update: maintainers list
  maintainers.yaml
Labels: dco-signoff: yes, needs-kind, lgtm, approved, size/XS

#91 update: maintainers list
  maintainers.yaml
Labels: dco-signoff: yes, needs-kind, lgtm, approved, size/XS

#92 update: maintainers list
  maintainers.yaml
Labels: dco-signoff: yes, needs-kind, lgtm, approved, size/XS

#96 update: maintainers list
  maintainers.yaml
Labels: dco-signoff: yes, needs-kind, lgtm, approved, size/XS

#97 cleanup: remove maintainers.yaml
  maintainers.yaml
Labels: dco-signoff: yes, needs-kind, lgtm, approved, size/L

#99 update(OWNERS): add jasondellaluce
  OWNERS
Labels: dco-signoff: yes, lgtm, approved, size/XS, kind/documentation
